#!/bin/bash -eux

readonly SEVICE_NAME=stream
readonly PROJECT_ID=music-coop
readonly GCP_ACCOUNT=skgm0301@gmail.com
readonly GOOGLE_COMPUTE_ZONE=asia-northeast1-a
readonly DOCKER_TAG="gcr.io/${PROJECT_ID}/${SEVICE_NAME}:latest"
readonly SERVICE_STATIC_IP="35.243.98.206"
# n1-standard-1 or f1-micro or something
readonly GCP_MACHINE_TYPE=n1-standard-1

__set_env () {
  gcloud auth login --brief ${GCP_ACCOUNT}
  gcloud config set project ${PROJECT_ID}
  gcloud config set compute/zone ${GOOGLE_COMPUTE_ZONE}
}

_bike_cloudbuild () {
  gcloud builds submit --tag ${DOCKER_TAG}
}

_bike_create-with-container () {
  gcloud compute instances create-with-container ${SEVICE_NAME} \
    --container-image ${DOCKER_TAG} \
    --zone ${GOOGLE_COMPUTE_ZONE} \
    --boot-disk-size 30 \
    --address ${SERVICE_STATIC_IP}
  gcloud compute instances add-tags ${SEVICE_NAME} \
    --zone ${GOOGLE_COMPUTE_ZONE} \
    --tags http-server,https-server,allow-rtmp-server
}

_bike_update-container () {
  gcloud compute instances update-container ${SEVICE_NAME} \
    --container-image ${DOCKER_TAG} \
    --zone ${GOOGLE_COMPUTE_ZONE}
}

_bike_build_and_update () {
  _bike_cloudbuild
  _bike_update-container
}

_bike_stop_instance () {
  gcloud compute instances stop ${SEVICE_NAME}
}

_bike_start_instance () {
  gcloud compute instances start ${SEVICE_NAME}
}

_bike_set-machine-type () {
  # 一度インスタンスを停止して変更
  _bike_stop_instance

  gcloud compute instances set-machine-type ${SEVICE_NAME} \
    --machine-type ${GCP_MACHINE_TYPE}

  _bike_start_instance
}

########################################

__set_env

for target in "$@"
do
  eval "_bike_${target}"
done

